### ISSUE TITLE
Gnome 45 support?

### ISSUE THREAD

**Issue by ionutbortis** [kazysmaster/gnome-shell-extension-disable-unredirect#27]
Hello there and thank you for this extension!

Are there any plans to support the upcoming Gnome Shell, version 45?

Unfortunately, because of esm modules, the updated extensions can only work with gnome 45. Here you can find the [port guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html).

Thanks!

PS: I see that you also have some other extensions. I also use the Lock Keys one. The Gnome 45 support question applies to rest, as well, I guess :sweat_smile:

**Comment by LasseRosenow** [comment]
Thanks for the great work! I am already on Gnome 45 and eagerly waiting for this extension :)

Any eta on when it will be released on [extensions.gnome.org](https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/)?

(Because if I install it from GitHub, it would immediately be updated from the gnome extensions application and thus go back to not compatible version :o)

**Comment by kazysmaster** [comment]
well.. probably together with lockkeys extension, I can actually submit sooner since it works.

**Comment by ghost** [comment]
any updates?

**Comment by ghost** [comment]
hit the extension site, thanks for your work!
